spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.137.39.91/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    #配置数据字段为空，则不传递到前台
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell

#日志配置
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: #日志文件的存放位置，默认命名 spring.log
#  file: #日志文件的存放位置并命名
#  level: #指定日志级别
#    com.person.sell.LoggerTest: debug #可以指定某个类的日志级别

wechat:
  mpAppId: wx3cc7bcd8b9d854c1
  mpAppSecret: 71a52df59608efa5625e6be038d7f964
  mchId:
  mchKey:
  keyPath:
  notifyUrl: