spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.137.39.91/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    #配置数据字段为空，则不传递到前台
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 10.137.39.91
    port: 6379
    #password 有密码配置密码
server:
  servlet:
    context-path: /sell

#日志配置
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: #日志文件的存放位置，默认命名 spring.log
#  file: #日志文件的存放位置并命名
#  level: #指定日志级别
#    com.person.sell.LoggerTest: debug #可以指定某个类的日志级别

wechat:
  mpAppId: wx3cc7bcd8b9d854c1
  mpAppSecret: 71a52df59608efa5625e6be038d7f964
  openAppId:
  openAppSecret:
  mchId:
  mchKey:
  keyPath:
  notifyUrl:
  templateId:
    orderStatus: 20HLWBCMn2gUbnKuTxYzyUmeCmSgNwPewKEyYKIcrXU
    #模板ID可以多个
projecturl:
  wechatMpAuthorize: http://hxxuyh.natappfree.cc
  WechatOpenAuthorize: http://hxxuyh.natappfree.cc
  sell: http://hxxuyh.natappfree.cc

#设置 mapper 包日志级别为 trace，会打印 sql 语句
logging:
  level:
    com.person.sell.dataobject.mapper: trace
#当 mybatis 使用 xml 方式编写 sql 时，指定 mapper 文件位置:
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.person.sell.dataobject.ProductCategory
  configuration:
    map-underscore-to-camel-case: true  #驼峰命名
    use-generated-keys: true            #数据操作后返回主键值
    use-column-label: true              #使用列别名代替列名